from thermal_regulation.envs.ant_thr_env import AntThermalRegulationEnv, AntSmallThermalRegulationEnv
from thermal_regulation.envs.low_gear_ant_thr_env import LowGearAntSmallThermalRegulationEnv, LowGearAntThermalRegulationEnv
from thermal_regulation.envs.ant_sensor_thr_env import SensorAntThermalRegulationEnv, SensorAntSmallThermalRegulationEnv
from thermal_regulation.envs.snake_thr_env import SnakeThermalRegulationEnv, SnakeSmallThermalRegulationEnv
from thermal_regulation.envs.swimmer_thr_env import SwimmerThermalRegulationEnv, SwimmerSmallThermalRegulationEnv
